### ISSUE TITLE
Expliciter le logiciel Merci Edgar

### ISSUE THREAD

**Issue by pblayo** [krichtof/markdown-cv#3]
> Fondateur du logiciel Merci Edgar

Ajouter quelques mot pour dire à quoi sert ce logiciel ? (moi-même je sais juste que c'est lié à de l'artistique)

**Comment by krichtof** [comment]
Done !
https://github.com/krichtof/markdown-cv/commit/6bab17df561462ff61771a2ef2c5c5969ba6bfef
